_common/lib: !include "../common/lib.yaml"

name:               ale-core-core
synopsis:           ALE - core
description:        ALE - core
<<:                 *meta

default-extensions: *def-ext

dependencies: *common-deps

library:
  source-dirs: src

  dependencies:
    - aeson                >= 1.1       && < 2
    - async                >= 2.1       && < 2.2
    - base64-bytestring    >= 1         && < 2
    - binary               >= 0.8.5.1   && < 1
    - bytestring           >= 0.10      && < 0.11
    - containers           >= 0.5
    # default cryptonite-0.23 has poor Ed25519 interface
    - cryptonite           >= 0.24
    - data-default
    - data-default         >= 0.7.1     && < 0.8
    - fmt                  >= 0.5       && < 1
    - hashable             >= 1.2       && < 1.3
    - hedgehog             >= 0.5.2     && < 1
    - http-api-data        >= 0.3       && < 1
    - lens                 >= 4         && < 5
    - log-warper           >= 1.8       && < 1.9
    - memory               >= 0.14      && < 0.15
    - mtl                  >= 2         && < 3
    - resourcet            >= 1.1       && < 1.2
    - serialise            == 0.1.*
    - serokell-util        >= 0.6
    - time                 >= 1.6       && < 2
    - text                 >= 1.2       && < 2
    - text-conversions     >= 0.3       && < 1
    - text-format          >= 0.3       && < 0.4
    - transformers-base
    - unordered-containers >= 0.2       && < 0.3
    - vector

tests:
  ale-core-core-test:
    <<: *test-common

    dependencies:
      - HUnit
      - hedgehog
      - tasty
      - tasty-discover     >= 4.1.1
      - tasty-hedgehog
      - tasty-hunit

      - ale-core-core
      - aeson
      - bytestring
      - cborg
      - cryptonite
      - data-default
      - hashable
      - lens
      - memory
      - mmorph
      - mtl
      - serialise
      - serokell-util
      - stringsearch
      - text
      - unordered-containers
